---
title: ""
---

Cross national indicators coming soon

SCAR aims to build a unique large scale database using new computational methods and supplement at-scale data collection with important national level case studies.

The foundational AMAR data (All Minorities at Risk) is the most extensive cross-national longitudinal data collection in the world about minorities, their actions and treatment by the state.  The data contains variables that will allow us to begin to explore varying discrimination and its correlates cross-nationally (Birnir et.al. 2018). 

We will apply the method to sort through large amount of information to code for political actions and treatment of over 1,200 AMAR groups. The development will also address theoretical issues that come with a fluid group-level variable like ethnicity. Once refined at the aggregate level this method can be applied at the sub-national level to gather nuanced local level data in local languages. 

The first publication to come out of this work is:
[Coding with the machines: machine-assisted coding of rare event data.](https://academic.oup.com/pnasnexus/article/3/5/pgae165/7659908) 2024. PNAS Nexus. 3(5):165.
